sudo: required
language: go

dist: bionic

go:
- "1.13"

script:
- docker buildx version
- TAG=${TRAVIS_TAG:=latest} make docker

before_script:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update -qy
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo systemctl start docker
  - ./hack/install-buildx.sh

after_success:
  - make docker-login
  - make docker-login-ghcr
  - make push
  - make push-ghcr
script:

before_deploy:
- echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  provider: script
  script: TAG=${TRAVIS_TAG} make docker-login docker-login-ghcr push push-ghcr
  on:
    tags: true
