sudo: required
language: go

dist: bionic

go:
- "1.13"

script:
- docker buildx version
- TAG=${TRAVIS_TAG:=latest} make docker

before_script:
  - ./hack/install-docker.sh
  - ./hack/install-buildx.sh

after_success:
  - make docker-login
  - make docker-login-ghcr
  - make push
  - make push-ghcr
script:

before_deploy:
- echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  provider: script
  script: TAG=${TRAVIS_TAG} make docker-login docker-login-ghcr push push-ghcr
  on:
    tags: true
