[[constraint]]
  name = "github.com/digitalocean/godo"
  version = "1.22.0"

[[constraint]]
  name = "github.com/packethost/packngo"
  version = "0.2.0"

[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "0.1.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/scaleway/scaleway-sdk-go"
  version = "1.0.0-beta.3"

[[constraint]]
  name = "github.com/inlets/inletsctl"
  version = "0.3.0"